name: toastino_example
description: Use example of Toastino library.
version: 0.0.1
author: Marco Bramini, Qurami <marco.bramini@qurami.com>
dependencies:
  angular2: ^3.1.0
  toastino:
    path: ..
dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: "^1.0.3"
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
- dart_to_js_script_rewriter