name: toastino_example
description: Use example of Toastino library.
version: 0.0.1
#homepage: https://www.example.com TODO
author: Marco Bramini <braminim@gmail.com>
dependencies:
  angular2: ^3.0.0
  toastino:
    path: ..
dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1