name: toastino_example
description: Use example of Toastino library.
version: 0.3.0
author: Marco Bramini, Qurami <marco.bramini@qurami.com>

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  angular: ^6.0.1
  toastino:
    path: ..

dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
