name: toastino_example
description: Use example of Toastino library.
version: 0.0.1
author: Marco Bramini, Qurami <marco.bramini@qurami.com>
dependencies:
  angular2: ^3.1.0
  toastino:
    path: ..
dev_dependencies:
  browser: ^0.10.0
transformers:
- angular2:
    entry_points: web/main.dart