name: toastino
description: Toast component written in AngularDart. Provides clear and easy to use notifying system.
version: 0.1.0
author: Marco Bramini, Qurami <marco.bramini@qurami.com>

dependencies:
  angular: ^4.0.0

transformers:
- angular
