name: toastino
description: Toast component written in AngularDart. Provides clear and easy to use notifying system.
version: 0.0.1
author: Marco Bramini, Qurami <marco.bramini@qurami.com>
dependencies:
  angular2: ^3.1.0
transformers:
- angular2:
    entry_points: web/main.dart