name: toastino
description: Toast component written in AngularDart. Provides clear and easy to use notifying system.
version: 0.0.1
#homepage: https://www.example.com TODO
author: Marco Bramini <braminim@gmail.com>
dependencies:
  angular2: ^3.0.0
dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1