name: toastino
description: Toast component written in AngularDart. Provides clear and easy to use notifying system.
version: 0.3.1
author: Marco Bramini, Qurami <marco.bramini@qurami.com>

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  angular: ^6.0.0
